automation:
  label: "Automation"
  class: automation
cloud-foundation:
  label: "Cloud Foundation"
  class: cloud-foundation
networking:
  label: "Networking"
  class: networking
security:
  label: "Security"
  class: security
