name: Site Backup

on:
  workflow_dispatch:
    inputs:
      note:
        description: "Optional note for this snapshot (e.g., 'pre-major-release')"
        required: false
  schedule:
    - cron: "0 7 * * *"   # daily at 07:00 UTC (optional; adjust or remove)

permissions:
  contents: write    # needed to create tags/releases

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Guard against Windows-reserved file 'NUL'
        run: |
          if [ -e "NUL" ] || [ -e "nul" ]; then
            echo "::error::Reserved filename 'NUL' detected in repo root. Delete it and re-run."
            exit 1
          fi

      - name: Timestamp & tag
        id: meta
        run: |
          TS="$(date +'%Y%m%d-%H%M%S')"
          NOTE="${{ github.event.inputs.note }}"
          [ -z "$NOTE" ] && NOTE="auto"
          TAG="snapshot-${NOTE}-${TS}"
          echo "ts=$TS"   >> $GITHUB_OUTPUT
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Using tag: $TAG"

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install Jekyll deps
        run: bundle install --jobs 4 --retry 3

      - name: Build site
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build --trace

      - name: Ensure zip is available
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Create archives (source & built site)
        run: |
          git archive --format=zip -o "backup-source-${{ steps.meta.outputs.tag }}.zip" HEAD
          (cd _site && zip -r "../backup-site-${{ steps.meta.outputs.tag }}.zip" .)
          sha256sum "backup-source-${{ steps.meta.outputs.tag }}.zip" "backup-site-${{ steps.meta.outputs.tag }}.zip" > "backup-${{ steps.meta.outputs.tag }}.sha256"

      - name: Upload artifacts (Actions run)
        uses: actions/upload-artifact@v4
        with:
          name: backup-${{ steps.meta.outputs.tag }}
          path: |
            backup-source-${{ steps.meta.outputs.tag }}.zip
            backup-site-${{ steps.meta.outputs.tag }}.zip
            backup-${{ steps.meta.outputs.tag }}.sha256

      - name: Create annotated tag
        run: |
          git tag -a "${{ steps.meta.outputs.tag }}" -m "Snapshot backup ${{ steps.meta.outputs.tag }}"
          git push origin "${{ steps.meta.outputs.tag }}"

      - name: Create GitHub Release with assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.meta.outputs.tag }}
          name: Snapshot ${{ steps.meta.outputs.tag }}
          body: |
            Automated snapshot of repository source and built site.
            Triggered by: ${{ github.actor }}
            Note: ${{ github.event.inputs.note || '' }}
          files: |
            backup-source-${{ steps.meta.outputs.tag }}.zip
            backup-site-${{ steps.meta.outputs.tag }}.zip
            backup-${{ steps.meta.outputs.tag }}.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
